### PR TITLE
Optional argument suggestion for AncStateEstMatrix.

### PR DESCRIPTION
**Pull request by TGuillerme**
Hi Graeme,

I've added an optional argument to the AncStateEstMatrix: `uncertainty.threshold` (default = `0`). This argument allows to specify a threshold value of scaled likelihood below which ancestral states reconstructions should be rejected (and replaced by `NA`). The increments holds in a couple of lines using the `max.lik` internal object that was already calculated.

I think this might be useful in some cases where you have three states characters and a `0.33...` scaled likelihood for each ancestral state. Your algorithm should normally convert that into a multistate character estimation but it seems (probably due to random seeds or roundings) that `rerootingMethod` often returns one state with a scaled likelihood of `0.33334` for example and thus this character state will be used in the returned (note that I think it also does that with two characters states with a `0.50...` scaled likelihood: it looks like often the `rerootingMethod` function returns `0.5000001` for one character and `0.4999999` for the other!).

Cheers,

T.

### CODE REVIEW

**Comment by TGuillerme** [comment]
Hi Graeme,

I've added a quick utility function `MakeMorphNexus`:

This functions *creates* a matrix in the same format as `ReadMorphNexus` output (i.e. a list with `$header`, `$matrix`, etc…). It intakes as argument the list elements from `ReadMorphNexus`’s output list (`header`, `ordering`, `weights`) than can be left as default (`header = ""`, `ordering = "unord"` and `weights = 1`; the max and min valuess are automatically calculated from the matrix).

Also (and I think this can be more useful) it can intake a list already generated by `ReadMorphNexus` and (basically combining the two matrices) which can be useful for example for adding the ancestral states matrix to the tips matrix. The function might look long but basically only the last 7 lines are doing something really. All the rest above is sanitizing functions that make sure that the output object matches the exact characteristics required for being passed to the other `Claddis` functions.

Might also be handy if one wants to quickly write a `NEXUS` file:
````r
## Just a matrix
my_matrix <-matrix(sample(c(0,1, 25, TRUE), 5, 5)
## This doesn't work!
WriteMorphNexus(my_matrix, file = "my_matrix.nex.tmp")
## This shoud work!
WriteMorphNexus(MakeMorphNexus(my_matrix), file = "my_matrix.nex.tmp")
## Remove tmp file
file.remove("my_matrix.nex.tmp")
````

**Comment by dwbapst** [comment]
Ah, I haven't looked at Thomas's code yet so I'm probably late to the party, but I wrote a function for a similar purpose a few months ago, to convert matrices already in memory in R into the appropriate Claddis format. I'll just post it here, in case its of use, or does anything that Thomas's code doesn't do already:

```
createCladdisNexus<-function(charMatrix){
	#where row are assumed to be taxa, and columns are chars
		#and rownames are assumed to be taxon names
	NTAX<-nrow(charMatrix)
	NCHAR<-ncol(charMatrix)
	SYMBOLS<-unique(unlist(charMatrix))
	# remove ? from symbols, sort
	SYMBOLS<-sort(SYMBOLS[SYMBOLS!="?"])
	# suppressing this line results in erroneous min/max values !!
	#convert SYMBOLS to space delimited vector
	SYMBOLS<-paste0(SYMBOLS,collapse=" ")
	#clean taxon names: replace spaces with _
	taxNames<-rownames(charMatrix)
	taxNames<-sapply(taxNames,gsub,pattern=" ",replacement="_")
	#create matrix
	matrixString<-vector()
	for(i in 1:NTAX){
		taxName<-taxNames[i]
		taxChars<-paste0(unlist(charMatrix[i,]),collapse="")
		matrixString[i]<-paste0(taxName,"  ",taxChars,"\n")
		}
	#collapse to a single string
	matrixString<-paste0(matrixString,collapse="")
	nexusContents<-paste0("#NEXUS\n\nBEGIN DATA;\n\tDIMENSIONS  NTAX=",
		NTAX," NCHAR=",NCHAR,';\n\t FORMAT SYMBOLS= "',
		SYMBOLS,'\" MISSING=? GAP=- ;\nMATRIX\n\n',
		matrixString,";\nEND;\n")
	return(nexusContents)
	}
```

**Comment by TGuillerme** [comment]
Ah! Yours might work better actually... I've just realised that my function does not work with a random matrix.
````r
## Just a matrix
my_matrix <-matrix(sample(c(0,1, 25, TRUE), 5, 5))
## This doesn't work!
WriteMorphNexus(my_matrix, file = "my_matrix.nex.tmp")
## This shoud work!... But it doesn't...
WriteMorphNexus(MakeMorphNexus(my_matrix), file = "my_matrix.nex.tmp")
```` 
Well never mind then...

**Comment by TGuillerme** [comment]
Okay, so far, this pull request includes:
 * Added an argument to `MorphDistMatrix.fast` allowing to choose which distance matrix(ces) to calculate: `distance = c("Raw", "GED", "Gower", "Max", "Comp")`. When `distance` has only one argument, the function outputs a `matrix`, otherwise, it outputs a `list` as before.
 * Minor bug fix to `MorphDistMatrix.fast` that didn't dealt with polymorphic characters properly when calculating the Gower distance.
 * Minor bug fix to `MorphDistMatrix` where the GED distance was not including the characters weighting.
 * Added an argument to `AncStateEstMatrix` allowing to put an acceptance threshold based on the scaled likelihood of the ancestral states estimations for accepting/rejecting the ancestral state estimation. Estimations below that threshold are replaced by `NA`. By default the argument is set to `uncertainty.threshold = 0` meaning that all the ancestral states estimations are accepted.

**Comment by graemetlloyd** [comment]
Hi Both,

So I've been a bit slow with this as I am both hesitant to add in lines I don't understand and because my git merge skills are zero and I already screwed up the last attempt (inadvertently overwriting Thomas's changes immediately). I have also already created conflicts by adding other changes so I've mostly been trying to make these "manually" and via private conversations with Thomas.

I will leave this open for now, but will probably close it once I've sorted some stuff out with Thomas.

Thanks for your input!

Cheers,


Graeme

**Comment by graemetlloyd** [comment]
Just realised that this has all been superseded by the major rewrite to Claddis so am closing the pull request.

**Pull request closed without merging**
